# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Individual Thought Patterns
#email: markngsayyao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mathematics, Statistics, Computer Science etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mollymr305.github.io" # the base hostname & protocol for your site
github_username:  mollymr305

# Build settings
markdown: kramdown